  export const newPrice = (nameStock, price) => {
    const name = nameStock.toLowerCase()
    if (
    name.indexOf("jbl") != -1 ||
    name.indexOf("marshall") != -1 ||
    name.indexOf("nothing ear") != -1 ||
    name.indexOf("nothing ear") != -1 ||
    name.indexOf("nothing cmf") != -1 ||
    name.indexOf("galaxy buds") != -1 ||
    name.indexOf("galaxy smart tag") != -1 ||
    name.indexOf("airpods pro") != -1 ||
    name.indexOf("airpods pro") != -1 ||
    name.indexOf("air pods pro") != -1 ||
    name.indexOf("air pods 2") != -1 ||
    name.indexOf("airpods 2") != -1 ||
    name.indexOf("airpods 2") != -1 ||
    name.indexOf("air pods 3") != -1 ||
    name.indexOf("airpods 3") != -1 ||
    name.indexOf("airpods 3") != -1 ||
    name.indexOf("pencil") != -1 ||
    name.indexOf("homepod") != -1 ||
    name.indexOf("redmi buds") != -1 ||
    name.indexOf("a05s ") != -1 ||
    name.indexOf("a05 ") != -1 ||
    name.indexOf("a15 ") != -1 ||
    name.indexOf("a25 ") != -1 ||
    name.indexOf("a24 ") != -1 ||
    name.indexOf("a54 ") != -1 ||
    name.indexOf("a35 ") != -1 ||
    name.indexOf("a34 ") != -1 ||
    name.indexOf("m34 ") != -1 ||
    name.indexOf("m54 ") != -1 ||
    name.indexOf("a55 ") != -1 ||
    name.indexOf("a550 ") != -1 ||
    name.indexOf("galaxy watch") != -1 ||
    name.indexOf("poco") != -1 ||
    name.indexOf("poco") != -1 ||
    name.indexOf("camon ") != -1 ||
    name.indexOf("spark ") != -1 ||
    name.indexOf("magic keyboard") != -1 ||
    name.indexOf("magic mouse") != -1 ||
    name.indexOf("djl ") != -1 ||
    name.indexOf("dji ") != -1 ||
    name.indexOf("dji ") != -1 ||
    name.indexOf("dji ") != -1 ||
    name.indexOf("sony wireless") != -1 ||
    name.indexOf("wireless wh") != -1 ||
    name.indexOf("watch 6") != -1 ||
    name.indexOf("tab a") != -1 ||
    name.indexOf("redmi") != -1 ||
    name.indexOf("watch") != -1 ||
    name.indexOf("rayban") != -1 ||
    name.indexOf("gopro") != -1 ||
    name.indexOf("oppo") != -1 ||
    name.indexOf("agm") != -1 ||
    name.indexOf("blackview") != -1 ||
    name.indexOf("insta ") != -1 ||
    name.indexOf("huawei") != -1 ||
    name.indexOf("huawei") != -1 ||
    name.indexOf("fujifilm") != -1 ||
    name.indexOf("beats") != -1 ||
    name.indexOf("infinix") != -1 ||
    name.indexOf("tecno") != -1 ||
    name.indexOf("realme") != -1 ||
    name.indexOf("polaroid") != -1 ||
    name.indexOf("sonos") != -1 ||
    name.indexOf("buds") != -1
    ) {
    return Number(price) + 300
    } else if (
    name.indexOf("se (2022) gen") != -1 ||
    name.indexOf("se (2023) gen") != -1 ||
    name.indexOf("se2 4") != -1 ||
    name.indexOf("watch se") != -1 ||
    name.indexOf("note") != -1 ||
    name.indexOf("se (2022) 64") != -1 ||
    name.indexOf("se (2022) 128") != -1 ||
    name.indexOf("se (2022) 256") != -1 ||
    name.indexOf("se 2") != -1 ||
    name.indexOf("se 3") != -1 ||
    name.indexOf("se3") != -1 ||
    name.indexOf("se 64") != -1 ||
    name.indexOf("se 128") != -1 ||
    name.indexOf("se 256") != -1 ||
    name.indexOf("11 64") != -1 ||
    name.indexOf("11 128") != -1 ||
    name.indexOf("asus") != -1 ||
    name.indexOf("zenfone") != -1 ||
    name.indexOf("zenfone") != -1 ||
    name.indexOf("mi ") != -1 ||
    name.indexOf("mi ") != -1 ||
    name.indexOf("airpods max") != -1 ||
    name.indexOf("air pods max") != -1 ||
    name.indexOf("airpods max") != -1 ||
    name.indexOf("airwrap ") != -1 ||
    name.indexOf("v1") != -1 ||
    name.indexOf("vented") != -1 ||
    name.indexOf("hd0") != -1 ||
    name.indexOf("hd1") != -1 ||
    name.indexOf("gen5 detect") != -1 ||
    name.indexOf("gen 5 detect") != -1 ||
    name.indexOf("rb0") != -1 ||
    name.indexOf("ht0") != -1 ||
    name.indexOf("hs0") != -1 ||
    name.indexOf("designed") != -1 ||
    name.indexOf("heapdphone") != -1 ||
    name.indexOf("ph04") != -1 ||
    name.indexOf("vacuum cleaner micro") != -1 ||
    name.indexOf("wash g1 ") != -1 ||
    name.indexOf("paddle brush") != -1 ||
    name.indexOf("supersonic hair") != -1 ||
    name.indexOf("air purifier") != -1 ||
    name.indexOf("nintendo") != -1 ||
    name.indexOf("oculus") != -1 ||
    name.indexOf("playstation") != -1 ||
    name.indexOf("playstation") != -1 ||
    name.indexOf("xbox") != -1 ||
    name.indexOf("ps5") != -1 ||
    name.indexOf("pico") != -1 ||
    name.indexOf("steam") != -1 ||
    name.indexOf("garmin") != -1 ||
    name.indexOf("google") != -1 ||
    name.indexOf("pixel") != -1 ||
    name.indexOf("xperia") != -1 ||
    name.indexOf("rog") != -1 ||
    name.indexOf("rog") != -1 ||
    name.indexOf("acer") != -1 ||
    name.indexOf("msi") != -1 ||
    name.indexOf("asus") != -1 ||
    name.indexOf("lenovo") != -1 ||
    name.indexOf("motorola") != -1 ||
    name.indexOf("oneplus") != -1 ||
    name.indexOf("redmagic") != -1 ||
    name.indexOf("nubia") != -1 ||
    name.indexOf("nothing phone") != -1 ||
    name.indexOf("honor") != -1 ||
    name.indexOf("redmi note") != -1 ||
    name.indexOf("ps portal") != -1 ||
    name.indexOf("hero 1") != -1
    ) {
    return Number(price) + 400
    } else if (
    name.indexOf("xr 64") != -1 ||
    name.indexOf("12 mini") != -1 ||
    name.indexOf("12 64") != -1 ||
    name.indexOf("12 128") != -1 ||
    name.indexOf("12 256") != -1 ||
    name.indexOf("12 512") != -1 ||
    name.indexOf("12 pro") != -1 ||
    name.indexOf("13 128") != -1 ||
    name.indexOf("13 pro") != -1 ||
    name.indexOf("12 pro max") != -1 ||
    name.indexOf("13 mini") != -1 ||
    name.indexOf("13 128") != -1 ||
    name.indexOf("13 256") != -1 ||
    name.indexOf("13 512") != -1 ||
    name.indexOf("14 128") != -1 ||
    name.indexOf("14 256") != -1 ||
    name.indexOf("14 512") != -1 ||
    name.indexOf("14 plus") != -1 ||
    name.indexOf("14 pro 128") != -1 ||
    name.indexOf("14 pro 256") != -1 ||
    name.indexOf("14 pro 512") != -1 ||
    name.indexOf("14 pro 1tb") != -1 ||
    name.indexOf("14 pro 1tb") != -1 ||
    name.indexOf("14 promax") != -1 ||
    name.indexOf("14 pro max") != -1 ||
    name.indexOf("15 128") != -1 ||
    name.indexOf("15 256") != -1 ||
    name.indexOf("15 512") != -1 ||
    name.indexOf("15 plus 128") != -1 ||
    name.indexOf("15 plus 256") != -1 ||
    name.indexOf("15 plus 512") != -1 ||
    name.indexOf("15 pro 128") != -1 ||
    name.indexOf("15 pro 256") != -1 ||
    name.indexOf("15 pro 512") != -1 ||
    name.indexOf("15 pro 1tb") != -1 ||
    name.indexOf("15 promax 256") != -1 ||
    name.indexOf("15 promax 512") != -1 ||
    name.indexOf("15 promax 1tb") != -1 ||
    name.indexOf("15 pro max 256") != -1 ||
    name.indexOf("15 pro max 512") != -1 ||
    name.indexOf("15 pro max 1tb") != -1 ||
    name.indexOf("15 pro max 1tb") != -1 ||
    name.indexOf("15 pro max 1tb") != -1 ||
    name.indexOf("s 9 4") != -1 ||
    name.indexOf("s9 4") != -1 ||
    name.indexOf("aw 9") != -1 ||
    name.indexOf("aw 9") != -1 ||
    name.indexOf("aw  9") != -1 ||
    name.indexOf("s 8 4") != -1 ||
    name.indexOf("aw series 8") != -1 ||
    name.indexOf("aw 8") != -1 ||
    name.indexOf("aw 8") != -1 ||
    name.indexOf("watch s8") != -1 ||
    name.indexOf("aw series 9") != -1 ||
    name.indexOf("ultra 2") != -1 ||
    name.indexOf("s21") != -1 ||
    name.indexOf("s22") != -1 ||
    name.indexOf("s23") != -1 ||
    name.indexOf("s24") != -1 ||
    name.indexOf("z flip") != -1 ||
    name.indexOf("z fold") != -1 ||
    name.indexOf("tab s") != -1 ||
    name.indexOf("microsoft") != -1 ||
    name[0] === 'u' && name.indexOf("ul ") != -1
    ) {
    return Number(price) + 500
    } else if (
    name.indexOf("ipad 9") != -1 ||
    name.indexOf("ipad 10") != -1 ||
    name.indexOf("ipad 9") != -1 ||
    name.indexOf("ipad 9") != -1 ||
    name.indexOf("ipad mini") != -1 ||
    name.indexOf("ipad air") != -1 ||
    name.indexOf("ipad pro") != -1 ||
    name.indexOf("ipad pro 12.9") != -1 ||
    name.indexOf("mac") != -1 ||
    name.indexOf("macbook") != -1 ||
    name.indexOf("book ") != -1 ||
    name.indexOf("mb") != -1 ||
    name.indexOf("13.6 m") != -1 ||
    name.indexOf("15 m") != -1 ||
    name.indexOf("mgn") != -1 ||
    name.indexOf("vision pro") != -1 ||
    name.indexOf("air 1") != -1 ||
    name.indexOf("pro 11 ") != -1 ||
    name.indexOf("pro 12.9 ") != -1 ||
    name.indexOf("mini 6 ") != -1
    ) {
      return Number(price) + 1200;
    } else {
    return `${price} 🟥 `;
    }
    };
    
  