export const returnAppleHi = (name) => {
  return (
    name.indexOf("AirPods") != -1 ||
    name.indexOf("Airpods") != -1 ||
    name.indexOf("Air Pods") != -1 ||
    name.indexOf("Pencil") != -1 ||
    name.indexOf("HomePod") != -1 ||
    name.indexOf("Watch SE") != -1 ||
    name.indexOf("SE (2023) Gen") != -1 ||
    name.indexOf("SE 2") != -1 ||
    name.indexOf("SE2 4") != -1 ||
    name.indexOf("Se3") != -1 ||
    name.indexOf("SE 64") != -1 ||
    name.indexOf("SE 128") != -1 ||
    name.indexOf("SE 256") != -1 ||
    name.indexOf("11 64") != -1 ||
    name.indexOf("11 128") != -1 ||
    name.indexOf("12 Mini") != -1 ||
    name.indexOf("12 64") != -1 ||
    name.indexOf("12 128") != -1 ||
    name.indexOf("12 256") != -1 ||
    name.indexOf("12 Pro ") != -1 ||
    name.indexOf("12 Pro Max") != -1 ||
    name.indexOf("13 Mini") != -1 ||
    name.indexOf("13 128") != -1 ||
    name.indexOf("13 256") != -1 ||
    name.indexOf("13 512") != -1 ||
    name.indexOf("14 128") != -1 ||
    name.indexOf("14 256") != -1 ||
    name.indexOf("14 512") != -1 ||
    name.indexOf("14 Plus") != -1 ||
    name.indexOf("14 Pro 128") != -1 ||
    name.indexOf("14 Pro 256") != -1 ||
    name.indexOf("14 Pro 512") != -1 ||
    name.indexOf("14 Pro 1Tb") != -1 ||
    name.indexOf("14 Pro 1TB") != -1 ||
    name.indexOf("14 Pro Max") != -1 ||
    name.indexOf("15 128") != -1 ||
    name.indexOf("15 256") != -1 ||
    name.indexOf("15 512") != -1 ||
    name.indexOf("iPad 9") != -1 ||
    name.indexOf("iPad 10") != -1 ||
    name.indexOf("iPad Mini 6") != -1 ||
    name.indexOf("iPad Air 5") != -1 ||
    name.indexOf("iPad Pro") != -1 ||
    name.indexOf("PRO 12.9") != -1 ||
    name.indexOf("PRO 11") != -1 ||
    name.indexOf("AIR 11") != -1 ||
    name.indexOf("AIR 13") != -1 ||
    name.indexOf("AIR 5") != -1 ||
    name.indexOf("AW Series 9") != -1 ||
    name.indexOf("AW 9") != -1 ||
    name.indexOf("AW  9") != -1 ||
    name.indexOf("S 9 ") != -1 ||
    name.indexOf("AW Series 8") != -1 ||
    name.indexOf("AW 8") != -1 ||
    name.indexOf("AW  8") != -1 ||
    name.indexOf("S 8 ") != -1 ||
    name.indexOf("UL ") != -1 ||
    name.indexOf("Mac") != -1 ||
    name.indexOf("15 Plus 128") != -1 ||
    name.indexOf("15 Plus 256") != -1 ||
    name.indexOf("15 Plus 512") != -1 ||
    name.indexOf("15 Pro 128") != -1 ||
    name.indexOf("15 Pro 256") != -1 ||
    name.indexOf("15 Pro 512") != -1 ||
    name.indexOf("15 Pro 1Tb") != -1 ||
    name.indexOf("15 ProMax 256") != -1 ||
    name.indexOf("15 ProMax 512") != -1 ||
    name.indexOf("15 ProMax 1Tb") != -1 ||
    name.indexOf("15 Pro Max 1TB") != -1 ||
    name.indexOf("15 Pro Max 1Tb") != -1 ||
    name.indexOf("iPad Pro 12.9") != -1 ||
    name.indexOf("Ultra 2") != -1 ||
    name.indexOf("Macbook") != -1 ||
    name.indexOf("Book ") != -1 ||
    name.indexOf("MB") != -1 ||
    name.indexOf("Vision Pro") != -1 ||
    name.indexOf("Watch S8") != -1 ||
    name.indexOf("Watch S9") != -1 ||
    name.indexOf("IPad 9") != -1 ||
    name.indexOf("Magic Keyboard") != -1 ||
    name.indexOf("MINI 6") != -1 ||
    name.indexOf("Air 13") != -1 ||
    name.indexOf("Air 15") != -1 ||
    name.indexOf("Pro 13") != -1
  );
};
